[project]
	dependencies = ["altair>=5.5.0", "polars>=1.32.2"]
	description = "Add your description here"
	name = "weather"
	readme = "README.md"
	requires-python = ">=3.12"
	version = "0.1.0"

[dependency-groups]
	dev = ["ipykernel>=6.30.1", "ruff>=0.12.8"]
